services:
  vscode:
    image: latex_dc:2023
    build: .
    volumes:
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh
      - ~/.gitconfig:/home/vscode/.gitconfig
    entrypoint: ["zsh", "-c", "while sleep 1000; do :; done"]
